### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by TherFdurdv32** [Tennis-Ball/Valorant-Aim-Assist#1]
Is this aimbot? How does this work and how do I install this?

**Comment by Tennis-Ball** [comment]
It is an in-the-works project exploring aim ASSIST in a research fashion. It's not traditional aimbot in that all measurements and calculations are taken externally, and the crosshair is never locked but rather adjusted in real time allowing the player to have full freedom of their gameplay. I'm not sure if I will release the complete source code or any executable to prevent potential cheating.

**Comment by TherFdurdv32** [comment]
Release it, I am willing to pay

**Comment by Tennis-Ball** [comment]
I am not looking to facilitate cheating in any way. If you are looking to conduct further research or are genuinely interested in the project, we can discuss on separate platform.
